### ISSUE TITLE
Update Docker Hub description from thre README.md

### ISSUE THREAD

**Issue by kelson42** [openzim/docker-publish-action#2]
Since we upload images, the synchronisation does not happen anymore and we have nothing or older versions of the README.md on Docker Hub.

It would be good if:
* The `README.md` is uploaded as well
* Maybe only for official releases
* Maybe if a `Docker.md` exists, we should prefer it.

https://github.com/peter-evans/dockerhub-description should help to do that easily.

**Comment by rgaudin** [comment]
That's right ; it would be a great addition. We can't reuse actions within actions though so the simplest way is probably to duplicate what this action does: a simple PATCH request to Dockerhub.

**Comment by kelson42** [comment]
@Nevish-302 If you are interested in working on this repository (which is pretty rare for external people). You might be interested to look at this ticket. The lack of implementation of this ticket is more and more annoying over time as we have no easy way for now to update hub.docker.com description page when we upload new Docker images.

**Comment by Nevish-302** [comment]
@kelson42 i am not sure how to do that, like you want me to update readme.md for this repository or something else.

**Comment by kelson42** [comment]
@Nevish-302 If you don't know how to fix it, then just leave it. Was just an idea.
